const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //code
  GET_GENDER_START: "GET_GENDER_START",
  GET_GENDER_SUCCESS: "GET_GENDER_SUCCESS",
  GET_GENDER_FAIL: "GET_GENDER_FAIL",

  GET_ROLE_START: "GET_ROLE_START",
  GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
  GET_ROLE_FAIL: "GET_ROLE_FAIL",

  GET_STATUS_START: "GET_STATUS_START",
  GET_STATUS_SUCCESS: "GET_STATUS_SUCCESS",
  GET_STATUS_FAIL: "GET_STATUS_FAIL",

  GET_TIME_START: "GET_TIME_START",
  GET_TIME_SUCCESS: "GET_TIME_SUCCESS",
  GET_TIME_FAIL: "GET_TIME_FAIL",

  GET_ACTION_START: "GET_ACTION_START",
  GET_ACTION_SUCCESS: "GET_ACTION_SUCCESS",
  GET_ACTION_FAIL: "GET_ACTION_FAIL",

  GET_STATUS_START: "GET_STATUS_START",
  GET_STATUS_SUCCESS: "GET_STATUS_SUCCESS",
  GET_STATUS_FAIL: "GET_STATUS_FAIL",
});

export default actionTypes;
